version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      jobspy:
        patterns:
          - "python-jobspy"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
